# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: pip install colorama, coverage, pytest, flake8
    displayName: 'Install development packages'
  - script: sudo apt install -y build-essential python-dev python3-dev libasound2-dev libjack-jackd2-dev
    displayName: 'Install python-rtmidi dependencies'
  - script: pip install mido, pygame, python-rtmidi
    displayName: 'Install dependencies'
  - script: setup.py install
    displayName: 'Install MIDIEvents'